import { IFlosCarmeli } from '../interfaces/IFlosCarmeli';

export const flosCarmeliData: IFlosCarmeli[] = [
  {
    id: 1,
    image: 'february.jpg',
    volume: 5,
    issue: 2,
    date: new Date(2023, 1),
    file: 'february.pdf',
    name: 'February 2023 - Edition',
  },
  {
    id: 2,
    image: 'march.jpg',
    volume: 5,
    issue: 3,
    date: new Date(2023, 2),
    file: 'march.pdf',
    name: 'March 2023 - Edition',
  },
  {
    id: 3,
    image: 'april.jpg',
    volume: 5,
    issue: 4,
    date: new Date(2023, 3),
    file: 'april.pdf',
    name: 'April 2023 - Edition',
  },
  {
    id: 4,
    image: 'may.jpg',
    volume: 5,
    issue: 5,
    date: new Date(2023, 4),
    file: 'may.pdf',
    name: 'May 2023 - Edition',
  },
  {
    id: 5,
    image: 'june.jpg',
    volume: 5,
    issue: 6,
    date: new Date(2023, 5),
    file: 'june.pdf',
    name: 'June 2023 - Edition',
  },
  {
    id: 6,
    image: 'july.jpg',
    volume: 5,
    issue: 7,
    date: new Date(2023, 6),
    file: 'july.pdf',
    name: 'July 2023 - Edition',
  },
  {
    id: 7,
    image: 'dec.jpg',
    volume: 5,
    issue: 8,
    date: new Date(2023, 11),
    file: 'dec.pdf',
    name: 'December 2023 - Edition',
  },
  {
    id: 8,
    image: 'jan.jpg',
    volume: 6,
    issue: 1,
    date: new Date(2024, 0),
    file: 'jan_2024.pdf',
    name: 'Janurary 2024 - Edition',
  },
  {
    id: 9,
    image: 'jan.jpg',
    volume: 6,
    issue: 2,
    date: new Date(2024, 1),
    file: 'feb_2024.pdf',
    name: 'February 2024 - Edition',
  },
  {
    id: 10,
    image: 'jan.jpg',
    volume: 6,
    issue: 3,
    date: new Date(2024, 2),
    file: 'mar_2024.pdf',
    name: 'March 2024 - Edition',
  },
  {
    id: 11,
    image: 'jan.jpg',
    volume: 6,
    issue: 4,
    date: new Date(2024, 3),
    file: 'apr_2024.pdf',
    name: 'April 2024 - Edition',
  },
  {
    id: 12,
    image: 'jan.jpg',
    volume: 6,
    issue: 5,
    date: new Date(2024, 4),
    file: 'may_2024.pdf',
    name: 'May 2024 - Edition',
  },
  {
    id: 13,
    image: 'jan.jpg',
    volume: 6,
    issue: 6,
    date: new Date(2024, 5),
    file: 'jun_2024.pdf',
    name: 'June 2024 - Edition',
  },
  {
    id: 14,
    image: 'jan.jpg',
    volume: 6,
    issue: 7,
    date: new Date(2024, 6),
    file: 'jul_2024.pdf',
    name: 'July 2024 - Edition',
  },
  {
    id: 15,
    image: 'jan.jpg',
    volume: 6,
    issue: 8,
    date: new Date(2024, 7),
    file: 'aug_2024.pdf',
    name: 'August 2024 - Edition',
  },
];
