import { IGallery } from '../interfaces/IGallery';

export const galleryData: IGallery[] = [
  {
    associationName: 'parish',
    logo: 'logo.png',
    albums: [
      {
        name: 'Feast 2023',
        date: new Date('2022-01-28'),
        thumbnailUrl: '/parish/Feast 2023/img1.jpg',
        images: [
          'img1.jpg',
          'img2.jpg',
          'img3.jpg',
          'img4.jpg',
          'img5.jpg',
          'img6.jpg',
          'img7.jpg',
          'img8.jpg',
          'img9.jpg',
          'img10.jpg',
          'img11.jpg',
          'img12.jpg',
          'img13.jpg',
          'img14.jpg',
          'img15.jpg',
          'img16.jpg',
          'img17.jpg',
          'img18.jpg',
          'img19.jpg',
          'img20.jpg',
        ],
      },
      {
        name: 'Feast of Corpus Chirsti',
        date: new Date('2023-06-29'),
        thumbnailUrl: '/parish/Feast of Corpus Chirsti/img1.jpg',
        images: ['corpuschristi.jpg'],
      },
      {
        name: 'Ezuthiniruthaal May 2023',
        date: new Date('2023-05-28'),
        thumbnailUrl: '/parish/Ezuthiniruthaal May 2023/img1.jpg',
        images: ['corpuschristi.jpg'],
      },
    ],
  },
  {
    associationName: 'Mount Carmel Youth',
    logo: 'logo.png',
    albums: [
      {
        name: 'Hallelujah 2022',
        date: new Date('2022-10-02'),
        thumbnailUrl: '/Mount Carmel Youth/Hallelujah 2022/IMG_3299.jpg',
        images: [
          'IMG_2781.jpg',
          'IMG_2745.jpg',
          'IMG_2837.jpg',
          'IMG_2842.jpg',
          'IMG_3299.jpg',
          'IMG_3014.jpg',
          'IMG_2723.jpg',
          'IMG_3289.jpg',
        ],
      },
    ],
  },
  {
    associationName: 'catechism',
    logo: 'logo.png',
    albums: [
      {
        name: 'Teacher_s Meeting',
        date: new Date('2022-06-01'),
        thumbnailUrl: '/catechism/Teacher_s Meeting/img2.jpeg',
        images: [
          'img1.jpeg',
          'img2.jpeg',
          'img3.jpeg',
          'img4.jpeg',
          'img5.jpeg',
          'img6.jpeg',
          'img7.jpeg',
          'img8.jpeg',
          'img9.jpeg',
          'img10.jpeg',
        ],
      },
      {
        name: 'Moments',
        date: new Date('2022-06-01'),
        thumbnailUrl: '/catechism/Moments/img10.jpg',
        images: [
          'img1.jpg',
          'img2.jpg',
          'img3.jpg',
          'img4.jpg',
          'img5.jpg',
          'img6.jpg',
          'img7.jpg',
          'img8.jpg',
          'img9.jpg',
          'img10.jpg',
        ],
      },
    ],
  },
  {
    associationName: 'Carmel Mercy Home',
    logo: 'logo.png',
    albums: [
      {
        name: 'Inauguration',
        date: new Date('2019-08-04'),
        thumbnailUrl: '/Carmel Mercy Home/Inauguration/img16.JPG',
        images: [
          'img1.JPG',
          'img2.JPG',
          'img3.JPG',
          'img4.JPG',
          'img5.JPG',
          'img6.JPG',
          'img7.JPG',
          'img8.JPG',
          'img9.JPG',
          'img10.JPG',
          'img11.JPG',
          'img12.JPG',
          'img13.JPG',
          'img14.JPG',
          'img15.JPG',
          'img16.JPG',
        ],
      },
    ],
  },
];
